---
title: "Santa Clara County Social Vulnerability Index Dashboard"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

<style>
.datatables{
    overflow: auto;
}
</style>

```{r global, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(leaflet)
library(plotly)
library(sf)
library(DT)
library(shinydashboard)
library(colorRamps)
library(mapboxapi)

data <- readRDS("scc_svi.rds")

variables <- data.frame(
  label = c(
    "Social Vulnerability Index",
    "% Below Poverty",
    "% Unemployed",
    "$ Per Capita Income",
    "% No High School Diploma",
    "% Aged 65 or Older",
    "% Aged 17 or Younger",
    "% Civilian with a Disability",
    "% Single-Parent Households",
    "% Minority",
    "% Speaks English 'Less than Well'",
    "% Multi-Unit Structures",
    "% Mobile Homes",
    "% Crowding",
    "% No Vehicle",
    "% Group Quarters",
    "% No Health Insurance"
  ),
  code = c(
    "SVI",
    "EP_POV",
    "EP_UNEMP",
    "EP_PCI",
    "EP_NOHSDP",
    "EP_AGE65",
    "EP_AGE17",
    "EP_DISABL",
    "EP_SNGPNT",
    "EP_MINRTY",
    "EP_LIMENG",
    "EP_MUNIT",
    "EP_MOBILE",
    "EP_CROWD",
    "EP_NOVEH",
    "EP_GROUPQ",
    "EP_UNINSUR"
  ),
  short = c(
    "SVI",
    "% Poverty",
    "% Unemployed",
    "$ Income",
    "% No Diploma",
    "% Elderly",
    "% Youth",
    "% Disability",
    "% Single Parent",
    "% Minority",
    "% Limited English",
    "% Multi Family",
    "% Mobile Home",
    "% Crowding",
    "% No Vehicle",
    "% Group Quarters",
    "% Uninsured"
  )
)

colors <- primary.colors(nrow(variables)+1, 3, no.white = T) %>% .[-1]

pal_list <- 
  1:nrow(variables) %>%
  map(function(x){
    tryCatch(
      colorNumeric(
        palette = colorRamp(c("#FFFFFF", colors[x]), interpolate = "spline"),
        domain = data %>% 
          pull(variables[x,2])
      ),
      error = function(e) NULL
    )
  })
```

Home
===================================== 

Inputs {.sidebar}
-----------------------------------------------------------------------

**Plot** - Each dot is a block group. Keep in mind that correlation is not causation. Select two variables to plot by:

```{r}
selectInput(
  "V1", 
  label = "X-axis variable", 
  choices = variables$label, 
  selected = variables$label[11]
)

selectInput(
  "V2", 
  label = "Y-axis variable", 
  choices = variables$label, 
  selected = variables$label[17]
)
```

**Map** - Block groups shown in color. Select layers on the right.

**Table** - Click on column headers to sort.

**About the data** - SVI is calculated using the CDC's [methodology](https://www.atsdr.cdc.gov/placeandhealth/svi/documentation/pdf/SVI2018Documentation-H.pdf). All data is from the American Communities Survey 2014-2018 5-year Detailed Tables:

- % Below Poverty: B17010, POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY FAMILY TYPE BY PRESENCE OF RELATED CHILDREN UNDER 18 YEARS BY AGE OF RELATED CHILDREN
- % Unemployed: B23025, EMPLOYMENT STATUS FOR THE POPULATION 16 YEARS AND OVER
- \$ Per Capita Income: B19301, PER CAPITA INCOME IN THE PAST 12 MONTHS (IN 2018 INFLATION-ADJUSTED DOLLARS)
- % No High School Diploma: B28006, EDUCATIONAL ATTAINMENT BY PRESENCE OF A COMPUTER AND TYPES OF INTERNET SUBSCRIPTION IN HOUSEHOLD
- % Aged 65 or Older: B01001, SEX BY AGE
- % Aged 17 or Younger: B01001, SEX BY AGE
- % Civilian with a Disability: C21007, AGE BY VETERAN STATUS BY POVERTY STATUS IN THE PAST 12 MONTHS BY DISABILITY STATUS FOR THE CIVILIAN POPULATION 18 YEARS AND OVER
- % Single-Parent Households: B11003, FAMILY TYPE BY PRESENCE AND AGE OF OWN CHILDREN UNDER 18 YEARS
- % Minority: B03002, HISPANIC OR LATINO ORIGIN BY RACE
- % Speaks English 'Less than Well': B16004, AGE BY LANGUAGE SPOKEN AT HOME BY ABILITY TO SPEAK ENGLISH FOR THE POPULATION 5 YEARS AND OVER
- % Multi-Unit Structures: B25024, UNITS IN STRUCTURE
- % Mobile Homes: B25024, UNITS IN STRUCTURE
- % Crowding: B25014, TENURE BY OCCUPANTS PER ROOM
- % No Vehicle: B25044, TENURE BY VEHICLES AVAILABLE
- % Group Quarters: B09019, HOUSEHOLD TYPE (INCLUDING LIVING ALONE) BY RELATIONSHIP
- % No Health Insurance: TYPES OF HEALTH INSURANCE COVERAGE BY AGE

Row {data-height=600}
-----------------------------------------------------------------------

### {.no-padding data-width=400}

```{r}
plotlyOutput("scatterplot")
```

```{r, context="server"}
output$scatterplot <- renderPlotly({
  
  scatter_data <-
    data %>% 
    st_set_geometry(NULL) %>% 
    select(
      CBG,
      V1 = variables$code[match(input$V1, variables$label)],
      V2 = variables$code[match(input$V2, variables$label)]
    ) %>% 
    filter(!is.na(V1), !is.na(V2)) %>% 
    mutate(
      trendline = fitted(lm(V2 ~ V1))
    )
  
  model <- summary(lm(V2 ~ V1, data = scatter_data))
  effect <- model$coefficients[2] %>% round(1)
  r2 <- (model$r.squared*100) %>% round()
  
  xlabel <- variables$short[match(input$V1, variables$label)]
  ylabel <- variables$short[match(input$V2, variables$label)]
  
  plot_ly(scatter_data) %>%
    add_trace(
      x = ~V1, 
      y = ~V2, 
      text = ~paste0("CBG: ", CBG),
      type = 'scatter', 
      mode = 'markers',
      showlegend = F
    ) %>% 
    add_trace(
      x = ~V1,
      y = ~trendline,
      type = 'scatter',
      mode = 'lines',
      line = list(simplify=F, size = 5, color = 'rgba(255, 165, 0, 1)'),
      showlegend = F,
      hoverinfo = "skip"
    ) %>%
    layout(
      title = list(
        text = paste0(
          "Trend: +1 in <b>",
          gsub("\\$ ","",xlabel),
          "</b> correlated with ",
          ifelse(
            effect > 0,
            "+",
            ""
          ),
          effect,
          " in <b>",
          gsub("\\$ ","",ylabel),
          "</b>\nFit: ",
          r2,
          "% of variation in ",
          gsub("\\$ ","",ylabel), 
          " explained by variation in ",
          gsub("\\$ ","",xlabel)
        ),
        font = list(size = 9)
      ),
      xaxis = list(
        title = xlabel,
        fixedrange = T
      ), 
      yaxis = list(
        title = ylabel,
        fixedrange = T
      ),
      margin = list(t = 65, l = 65, b = 65)
    ) %>% 
    config(displayModeBar = F)
  
})
```

### {.no-padding data-width=600}

```{r}
leafletOutput("map")
```

```{r, context="server"}
output$map <- renderLeaflet({
  map <- 
    leaflet() %>% 
    addProviderTiles(providers$CartoDB.Positron, group = "Minimal Basemap") %>%
    addMapboxTiles(
      style_id = "satellite-streets-v11",
      username = "mapbox",
      access_token = "YOUR-KEY-HERE",
      group = "Satellite Basemap"
    ) %>% 
    addMapboxTiles(
      style_id = "streets-v11",
      username = "mapbox",
      access_token = "YOUR-KEY-HERE",
      group = "Default Basemap"
    ) %>% 
    addMapPane("blocks", 420) %>% 
    addLayersControl(
      baseGroups = variables$short,
      overlayGroups = c(
        "Minimal Basemap",
        "Satellite Basemap",
        "Default Basemap"
      ),
      options = layersControlOptions(collapsed = FALSE)
    ) %>%
    showGroup("SVI") %>% 
    hideGroup("Satellite Basemap") %>% 
    hideGroup("Minimal Basemap")
  
  for(x in 1:nrow(variables)){
    map <- 
      map %>% 
      addPolygons(
        data = data,
        fillColor = pal_list[[x]](data %>% pull(variables[x,2])),
        color = "white",
        weight = 0.5,
        opacity = 0.5,
        fillOpacity = 0.7,
        group = variables[x, 3],
        label = paste0(data$CBG,": ", data %>% pull(variables[x,2]) %>% round(2))
      )
  }
  
  map
  
})
```

```{r}
observeEvent(input$map_groups,{
  leafletProxy('map') %>% 
    removeControl(layerId = "legend")
  
  for(x in 1:nrow(variables)){
    
    if(variables[x,3] %in% isolate(input$map_groups)){
      
      leafletProxy('map') %>% 
        addLegend(
          data = data,
          pal = pal_list[[x]],
          values = data %>% pull(variables[x,2]),
          title = variables[x,3],
          opacity = 0.5,
          layerId = "legend",
          position = "topleft"
        )
      
    }
    
  }
})
```

```{r, context="server"}
observeEvent(input$table_rows_selected,{
  
  leafletProxy('map') %>% 
    removeShape(layerId = "select")
  
  row <- input$table_rows_selected
  
  if(length(row)){
    
    leafletProxy('map') %>% 
      addPolygons(
        data = data[row,],
        fill = F,
        color = "black",
        weight = 2,
        opacity = 1,
        layerId = "select",
        options = 
          pathOptions(
            pane = "blocks"
          )
      ) %>% 
      flyTo(
        lng = data[row,] %>% st_centroid() %>% st_coordinates() %>% .[1],
        lat = data[row,] %>% st_centroid() %>% st_coordinates() %>% .[2], 
        zoom = isolate(input$map_zoom)
      )
  }

}, ignoreInit = T, ignoreNULL = F)
```

Row {data-height=400}
-----------------------------------------------------------------------

### {.no-padding}

```{r}
dataTableOutput("table")
```

```{r}
output$table <- renderDataTable(
  
  test <- data %>%
    st_set_geometry(NULL) %>% 
    select(
      CBG,
      variables$code
    ) %>% 
    mutate_at(
      vars(variables$code),
      ~round(.,1)
    ) %>% 
    rename_all(
      funs(
        gsub(
          "X",
          "%",
          gsub(
            "\\.",
            " ",
            make.names(
              c(
              "CBG",
              variables$short
              )
            )
          )
        )
      )
    ) %>% 
    rename("$ Income" = "%  Income"),
  options = list(
    pageLength = 5,
    order = list(2, 'dsc'),
    dom = 'tp'
  ),
  rownames = F,
  selection = 'single'
  
)
```